# Generated by Django 4.1.3 on 2022-11-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='multiply_items',
        ),
        migrations.AddField(
            model_name='order',
            name='multiply_items',
            field=models.ManyToManyField(to='api.item'),
        ),
    ]
