# Generated by Django 4.1.3 on 2022-11-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_multiply_items_order_multiply_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('euro', 'euros'), ('usd', 'dollars')], default='euro', max_length=10),
        ),
    ]
