# Generated by Django 4.1.3 on 2022-11-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('eur', 'euros'), ('usd', 'dollars')], default='eur', max_length=10),
        ),
    ]
